spring:
  application:
    name: messenger

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=chat
    username: postgres
    password: 3614
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
